server:
  port: 9999
spring:
  application:
    name: util
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/www/ecampus/static/
      ,file:///D:\project\zj-websocket\zj-websocket-chat/files/
    
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/zj_websocket?characterEncoding=utf-8
    username: root
    password: root

mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.zj.modules.domain
  type-handlers-package: com.zj.modules.mapper
  mapper-locations: classpath:com.zj.modules.mapper/*.xml
  
  
#test 支付配置
#payment.wx.useSandbox=false
#payment.wx.notifyUrl=http://21742pa841.51mypc.cn:46064/lz/om/payment/wx/syncNotify
#payment.wx.certPath=/home/certs/
#
#payment.alipay.gatewayUrl=https://openapi.alipaydev.com/gateway.do
#payment.alipay.charset=utf-8
#payment.alipay.signType=RSA2
#payment.alipay.notifyUrl=http://21742pa841.51mypc.cn:46064/lz/om/payment/alipay/syncNotify
#payment.alipay.returnUrl=http://192.168.2.198:7777/service-center/my-order

#product
#payment.wx.UseSandbox=false
#payment.wx.notifyUrl=http://21742pa841.51mypc.cn:46064/lz/om/payment/wx/syncNotify
#payment.wx.certPath=/home/certs/

#payment.alipay.gatewayUrl=https://openapi.alipay.com/gateway.do
#payment.alipay.charset=utf-8
#payment.alipay.signType=RSA2-
#payment.alipay.notifyUrl=http://21742pa841.51mypc.cn:46064/lz/om/payment/alipay/syncNotify
#payment.alipay.returnUrl=http://192.168.1.230:7777/service-center/my-order
    
    
    